### PR TITLE
ensure rules have non-overlapping paths (closes #12)

### LINKED ISSUE #12: non-matching rule applied (interfering state kept between failing rule attempts?)
Possibly a dupe of https://github.com/apertium/apertium-lex-tools/issues/1 though I haven't checked closely.

This seems to be happening: If you have a rule1 that tries to apply `<or>A B</or> C` (where A/B/C are `<match>` elements) and A matches but C fails, and then a rule2 that tries to match `B` where `B` is not in input, then lrx-proc will apply rule2 where it should have failed.

Reproduce with:

```sh
$ lrx-comp foo.lrx foo.lrx.bin
3: 78@83
$ echo '^c<a>/c<a>$ ^w<n>/want<n>/got<n>$' | lrx-proc -t -m foo.lrx.bin
2:SELECT:2.00000:w<n>:got<n>
^c<a>/c<a>$ ^w<n>/got<n>$
```

where `foo.lrx` contains

```xml
<rules>
  <rule weight="2.0">                    <!-- rule1 -->
    <or>
      <match lemma="c"/>                 <!-- A -->
      <match tags="unseen"/>             <!-- B -->
    </or>
    <match lemma="salkdfj" tags="adv.*"> <!-- C -->
      <select lemma="lksajfdlk"/>
    </match>
  </rule>

  <rule><match lemma="w" tags="n"><select lemma="want"/></match></rule>
  <rule weight="2.0">                    <!-- rule2 -->
    <match tags="unseen"/>               <!-- B -->
    <match lemma="w" tags="n">
      <select lemma="got"/>
    </match>
  </rule>
</rules>
```

### PR DESCRIPTION
**Pull request by mr-martian**

### CODE REVIEW

**Comment by TinoDidriksen** [comment]
I'm not a transducer expert, but what will this help? If it blindly adds an epsilon, then surely that doesn't change anything because the added epsilons are identical and can be collapsed, leading to the same bug?

**Comment by jonorthwash** [comment]
Also, @mr-martian, could you clarify why rules shouldn't have overlapping paths?

**Comment by mr-martian** [comment]
@jonorthwash There's some examples in #12 where if two rules have the same beginning and the paths overlap, for example a rule that matches (A|B)C and one that matches BD, then because the paths overlap, the second rule can match AD.

@TinoDidriksen insertNewSingleTransduction adds a separate path even if it could be collapsed.

**Comment by jonorthwash** [comment]
> if two rules have the same beginning and the paths overlap, for example a rule that matches (A|B)C and one that matches BD, then because the paths overlap, the second rule can match AD.

Oh, that's a pretty serious bug to my thinking.

**Comment by jonorthwash** [comment]
@unhammer, thoughts?

**Comment by unhammer** [comment]
If `lrx-comp` doesn't minimise after `insertNewSingleTransduction`, this should work. It does seem to do the right thing on the example from https://github.com/apertium/apertium-lex-tools/issues/12#issuecomment-446603521 , after compiling this pr I get:

after-pr-18

and it correctly blocks rule 2:
```
$ echo '^context<seen>/context<seen>$ ^Y<n>/Y<n>/want<n>$'| lrx-proc -t before.lrx.bin
2:SELECT<2>:Y<n>:<select>Y<ANY_TAG>
^context<seen>/context<seen>$ ^Y<n>/Y<n>$

$ echo '^context<seen>/context<seen>$ ^Y<n>/Y<n>/want<n>$'| lrx-proc -t after-pr-18.lrx.bin
^context<seen>/context<seen>$ ^Y<n>/Y<n>/want<n>$`
```

I haven't seen any diffs yet on 117493 lines of nob→nno, so that's good (rules in nno-nob are written with this bug in mind, so no diffs are expected – I do see a difference if I start introducing overlapping `<or>` sets).

File size increased 54K→60K on nob-nno.autolex.bin, and 103K→127K on sme-sma.autolex.bin, seems acceptable. 

But speed gets a bit worse, 500 lines of biltrans output takes 10.6s instead of 7,9s, and currently lrx-proc is the slowest program in pipeline (looking at htop while running nob→nno over a corpus, I see lrx-proc at 100% and cg-proc at 25%).

**Pull request merged**
